# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
target 'VSP_0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #Given pod thingy from aws.
  pod 'AWSMobileClient', '~> 2.6.13'
  pod 'AWSAuthCore', '~> 2.6.13'
  pod 'AWSAPIGateway', '~> 2.6.13'


  # Pods for VSP_0

  target 'VSP_0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VSP_0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
